name: Deploy to Azure Blob Storage

on:
  push:
    branches:
      - main  # Adjust this to match your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true # Set to true if you use the extended version of Hugo

    - name: Build Site
      run: hugo

    - name: List output
      run: ls -l public
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          pwd
          ls
          az storage blob upload-batch --account-name hugo69  --auth-mode key -d '$web' -s . --overwrite
